import { mkdir, readFile, writeFile, copyFile } from 'node:fs/promises';
import { resolve, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { deflateSync } from 'node:zlib';

const root = fileURLToPath(new URL('../', import.meta.url));
const target = resolve(root, 'dist/assets');
await mkdir(resolve(target, 'fonts'), { recursive: true });
let css = '/* Self-hosted fonts; licenses in assets/fonts. Generated by tools/assets.mjs. */\n';
for (const [family, weights] of [
  ['chakra-petch', [400, 600, 700]],
  ['space-mono', [400, 700]],
]) {
  const source = resolve(root, 'node_modules/@fontsource', family);
  for (const weight of weights) {
    let text = await readFile(resolve(source, `${weight}.css`), 'utf8');
    for (const [, file] of text.matchAll(/url\(['"]?(\.\/files\/[^'"\s)]+)['"]?\)/g)) {
      await copyFile(resolve(source, file), resolve(target, 'fonts', basename(file)));
    }
    text = text.replaceAll('./files/', '../assets/fonts/');
    css += `${text}\n`;
  }
  await copyFile(resolve(source, 'LICENSE'), resolve(target, 'fonts', `${family}-LICENSE.txt`));
}
await writeFile(resolve(root, 'dist/styles/fonts.css'), css);

function chunk(type, data) {
  const bytes = Buffer.concat([Buffer.from(type), data]);
  let crc = 0xffffffff;
  for (const byte of bytes) {
    crc ^= byte;
    for (let i = 0; i < 8; i++) crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0);
  }
  const header = Buffer.alloc(4),
    tail = Buffer.alloc(4);
  header.writeUInt32BE(data.length);
  tail.writeUInt32BE((crc ^ 0xffffffff) >>> 0);
  return Buffer.concat([header, bytes, tail]);
}
function inPolygon(x, y, points) {
  let inside = false;
  for (let i = 0, j = points.length - 1; i < points.length; j = i++) {
    const [xi, yi] = points[i],
      [xj, yj] = points[j];
    if (yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}
// Rasterize the existing geometric favicon, keeping its silhouette inside the mask-safe area.
for (const size of [192, 512]) {
  const raw = Buffer.alloc((size * 3 + 1) * size);
  for (let y = 0; y < size; y++)
    for (let x = 0; x < size; x++) {
      const px = ((x + 0.5) * 64) / size,
        py = ((y + 0.5) * 64) / size;
      let color = [9, 11, 24];
      if (
        inPolygon(px, py, [
          [13, 15],
          [28, 23],
          [36, 46],
          [18, 38],
        ]) ||
        inPolygon(px, py, [
          [51, 15],
          [36, 23],
          [28, 46],
          [46, 38],
        ])
      )
        color = [255, 61, 141];
      if ((px - 25) ** 2 + (py - 31) ** 2 < 9 || (px - 39) ** 2 + (py - 31) ** 2 < 9)
        color = [111, 255, 233];
      const offset = y * (size * 3 + 1) + 1 + x * 3;
      raw.set(color, offset);
    }
  const header = Buffer.alloc(13);
  header.writeUInt32BE(size, 0);
  header.writeUInt32BE(size, 4);
  header[8] = 8;
  header[9] = 2;
  await writeFile(
    resolve(target, `icon-${size}.png`),
    Buffer.concat([
      Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]),
      chunk('IHDR', header),
      chunk('IDAT', deflateSync(raw)),
      chunk('IEND', Buffer.alloc(0)),
    ]),
  );
}
console.log(`Generated offline fonts and icons in ${dirname(target)}.`);
