import { createHash } from 'node:crypto';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { resolve, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../dist/', import.meta.url));
async function walk(directory) {
  const files = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = resolve(directory, entry.name);
    if (entry.isDirectory()) files.push(...(await walk(path)));
    else if (entry.name !== 'precache-manifest.js') files.push(path);
  }
  return files;
}
const hash = createHash('sha256');
const files = (await walk(root)).sort();
for (const file of files) {
  hash.update(relative(root, file));
  hash.update(await readFile(file));
}
const manifest = {
  revision: hash.digest('hex').slice(0, 16),
  files: files.map((file) => `./${relative(root, file).split(sep).join('/')}`),
};
await writeFile(
  resolve(root, 'precache-manifest.js'),
  `/* Generated by npm run precache; do not edit. */\nself.__PRECACHE = ${JSON.stringify(manifest, null, 2)};\n`,
);
console.log(`Precached ${manifest.files.length} assets, revision ${manifest.revision}.`);
